const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const path=require('path'),root=path.resolve(__dirname,'..');
const ctx={window:{},document:{readyState:'loading',addEventListener(){}},matchMedia:()=>({matches:false}),localStorage:{getItem:()=>null}};vm.createContext(ctx);
for(const f of ['avatar-studio','captain-map'])vm.runInContext(fs.readFileSync(root+'/dist/'+f+'.js','utf8'),ctx);
const studio=ctx.window.CaptainStudio,clean=studio.clean({hair:'red',hat:'injected',variant:'../../outside',glasses:'gold-glasses',adjustments:{glasses:{x:2,y:-2,scale:8}}});
assert.equal(clean.hair,'original');assert.equal(clean.hat,undefined);assert.equal(clean.variant,undefined);assert.equal(clean.glasses,undefined);assert.equal(clean.adjustments,undefined);
const mask=new Uint8Array(31*31);for(let y=0;y<31;y++)for(let x=0;x<15;x++)mask[y*31+x]=1;const soft=studio.featherMask(mask,31,31);assert(soft[15*31+14]>.5);assert(soft[15*31+15]>0 && soft[15*31+15]<.5);for(let x=8;x<23;x++)assert(soft[15*31+x]>=soft[15*31+x+1]);
for(const group of ['female','male'])for(let i=1;i<=25;i++)assert(fs.existsSync(root+'/dist/assets/studio/extra-'+group+'-'+String(i).padStart(3,'0')+'.webp'));
const route=[{lat:0,lng:0},{lat:1,lng:2},{lat:2,lng:1}],sample=ctx.window.CaptainMap.sample;
assert.equal(sample([],0),null);assert.equal(sample(route,0).action,'map');const walking=sample(route,5000);assert.equal(walking.action,'walk');assert(walking.position.lat>0&&walking.position.lat<1);assert(walking.position.lng>0&&walking.position.lng<2);
const visited=new Set();for(let t=0;t<40000;t+=100){const s=sample(route,t);if(s.action!=='walk')visited.add(s.position.lat+','+s.position.lng);}assert.deepEqual([...visited].slice(0,3),['0,0','1,2','2,1']);
assert.equal(sample([route[0]],1000).action,'map');
console.log('PASS: hair-only options and continuous hairline feather, 50 new hairstyles, safe appearance IDs and ordered Captain route');
