import assert from 'node:assert/strict';
import {attendeesFor,allocateCost,parseMapsUrl,isGoogleMapsUrl,personStops} from '../dist/travel-utils.js';
const people=[{id:'a'},{id:'b'},{id:'c'}];
assert.equal(attendeesFor({participant_ids:null},people).length,3);
assert.deepEqual(attendeesFor({participant_ids:['b']},people),[{id:'b'}]);
assert.deepEqual(allocateCost({settlement_enabled:false,cost_won:10001},people),{});
const split=allocateCost({settlement_enabled:true,cost_won:10001,participant_ids:['a','b']},people);
assert.equal(split.a+split.b,10001);assert.equal(split.c,undefined);
assert.deepEqual(allocateCost({settlement_enabled:true,cost_won:100,participant_ids:['b','c'],split_ratios:{b:30,c:70}},people),{b:30,c:70});
assert.deepEqual(allocateCost({settlement_enabled:true,cost_won:101,participant_ids:['b'],split_ratios:{a:0,b:100}},people),{b:101});
const stops=[{id:1,participant_ids:null},{id:2,participant_ids:['a']},{id:3,participant_ids:['b']},{id:4,participant_ids:null}];
assert.deepEqual(personStops(stops,'a').map(x=>x.id),[1,2,4]);assert.deepEqual(personStops(stops,'b').map(x=>x.id),[1,3,4]);
assert.equal(parseMapsUrl('https://www.google.com/maps/search/?api=1&query=Airport&query_place_id=ChItest').placeId,'ChItest');
assert.deepEqual(parseMapsUrl('https://maps.google.com/?q=37.46,126.44').location,{lat:37.46,lng:126.44});
assert.equal(parseMapsUrl('https://www.google.com/maps/place/Kyoto+Station/@34.9,135.7,15z/data=!3d34.985!4d135.758').name,'Kyoto Station');
assert.equal(parseMapsUrl('https://maps.app.goo.gl/example').short,true);
for(const url of ['javascript:alert(1)','https://google.com.evil.test/maps','https://www.google.com@evil.test/maps','https://www.google.com:444/maps','https://example.com','https://goo.gl/unrelated'])assert.equal(isGoogleMapsUrl(url),false,url);
assert.throws(()=>parseMapsUrl('https://maps.google.com/?q=100,200'));
console.log('PASS: attendee splits, rejoining routes, opt-in accounting, exact rounding and Google URL parsing');
